### ISSUE TITLE
Generation/version missing in errorhandling

### ISSUE THREAD

**Issue by leo-baltus** [GoogleCloudPlatform/berglas#104]
While testing I stumbled on this:
```
RW_PASSWD=berglas://berglas-store/foo#582554393671996 go run my/main.go
2020/02/27 16:36:10 failed to access secret berglas-store/foo: failed to access secret: secret does not exist
```
So it is not reporting the generation or version which can be very helpful when debugging. 
https://github.com/GoogleCloudPlatform/berglas/blob/f168b3ab80a04f3f030eedf09173b00d5afd6425/pkg/berglas/resolver.go#L72

**Comment by sethvargo** [comment]
Fixed as part of https://github.com/GoogleCloudPlatform/berglas/commit/a1952ecb6fb282b33871ef786b07787ed285d037
