### ISSUE TITLE
gcloud functions deploy berglas-secrets-webhook fails

### ISSUE THREAD

**Issue by noamhurwitz** [GoogleCloudPlatform/berglas#108]
```
Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: go: finding github.com/kr/pretty v0.2.0
```

**Comment by saranicole** [comment]
@noamhurwitz  are you sure you're executing the deploy in the examples/kubernetes directory?  I was able to deploy this function successfully just now so I don't think it's the code.

**Comment by noamhurwitz** [comment]
yeah i got it working, i was missingly the webhook config. thanks
