### ISSUE TITLE
Is berglas planning to support Secret Manager as a backend for the Webhook?

### ISSUE THREAD

**Issue by martykuentzel** [GoogleCloudPlatform/berglas#112]
Hi,
we are looking into Google's Secret Manager for our secrets. Currently there is no way to combine Secret Manager with Kubernetes. Are you planning with Berglas to support a Kubernetes Webhook that retrieves the Secrets from Secret Manager like you did with gcs/kms ?

Best regards
Marty

**Comment by sethvargo** [comment]
Hi @martykuentzel 

Berglas already supports Secret Manager. Use the sm:// prefix instead of berglas:// anywhere. Make sure you're running a recent version.
