### ISSUE TITLE
Not able to upload the rsa.key

### ISSUE THREAD

**Issue by mukgarg-lb** [GoogleCloudPlatform/berglas#115]
Hi,

When i tried to run berglas create gs://xxxx/xx <#rsakey>

it's throwing error bad flag syntax: -----BEGIN RSA PRIVATE KEY-----

Not sure i am following the right steps.

Can you please help here?

**Comment by mukgarg-lb** [comment]
Looked at the https://github.com/GoogleCloudPlatform/berglas/issues/97 and tried 
cat my-private-rsa-key | berglas create --key ${KMS_KEY} ${BUCKET_ID}/MY_PRIVATE_RSA_KEY -
but only uploading the -----BEGIN RSA PRIVATE KEY-----

**Comment by sethvargo** [comment]
You have to use the "read from file" syntax for multiline files:

```text
berglas create gs://bucket/secret --key projects/... @/path/to/key.rsa
```

Note the leading `@` - this tells Berglas to interpret the value as a filepath. 

You might also be interested in [Secret Manager](https://cloud.google.com/secret-manager).
