### ISSUE TITLE
UI Support

### ISSUE THREAD

**Issue by cemo** [GoogleCloudPlatform/berglas#12]
UI support would be awesome. Each user can deploy into either GAE or GKE.

**Comment by sethvargo** [comment]
Hi @cemo 

Thanks for the feedback. Part of [Berglas' threat model](https://github.com/GoogleCloudPlatform/berglas/blob/master/doc/threat-model.md#entropy) relies on local system entropy to generate keys. Running Berglas as a service is not recommended, which would be a requirement for a UI. As such, I don't think we're going to offer a UI. 

Thank you for the feedback though!

**Comment by cemo** [comment]
I have not enough knowledge on security however we need a service which is counterpart of AWS Systems Manager Parameter Store or like other Cloud's solutions.
