### ISSUE TITLE
0.5.3 download link is not available

### ISSUE THREAD

**Issue by jak** [GoogleCloudPlatform/berglas#125]
We download specific versions and check against a sha256sum we generate, so we can trust our reproducible builds.

Unlike previous releases, 0.5.3 (released 2 days ago) is not available: https://storage.googleapis.com/berglas/0.5.3/linux_amd64/berglas

As an aside, it would be great if you also provided a checksum of the binary so we could check it :smile:

**Comment by sethvargo** [comment]
Ah. I renamed the branch from master -> main and that appears to have broken some automation. Investigating...

**Comment by sethvargo** [comment]
Fixed - all the CI/CD is open source and uses GitHub Actions now 😄
