### ISSUE TITLE
Unable to store multiline passwords into SM

### ISSUE THREAD

**Issue by dennybaa** [GoogleCloudPlatform/berglas#131]
Hello, just picks up only the first line

**Comment by sethvargo** [comment]
Duplicate of #115

**Comment by dennybaa** [comment]
Hmm. I got this. But it's a bug anyways and it's closed) Or you may call it a feature. Nevermind.

**Comment by dennybaa** [comment]
And it's annoying! What do you suggest to temporary store secrets on disk)

**Comment by dennybaa** [comment]
@sethvargo ?
