### ISSUE TITLE
Possibility to grant access to all secrets in GC Secret Manager

### ISSUE THREAD

**Issue by bayerlse** [GoogleCloudPlatform/berglas#140]
Hey there.

Very nice project! Is there a possibility to grant berglas access to all secrets in GC Secret Manager?
It's like a little overhead to always go to the connect to the cluster and manually grant berglas permission to access a secret in Secret Manager, expeccially when there are created new secrets very often.

Thanks in advance!

**Comment by sethvargo** [comment]
Hi @bayerlse - what do you mean by "grant berglas access to all secrets in GC Secret Manager"?

**Comment by bayerlse** [comment]
Hey sethvargo, thanks for you answer. I was wrong, sorry for that. I thought I have to grant berglas access to each secret manually, but its not the case.

Closing because of that.
