### ISSUE TITLE
Build in CA cert for Google services

### ISSUE THREAD

**Issue by jtyr** [GoogleCloudPlatform/berglas#144]
I'm aware of the fact that Berglas requires CA certificates in order to be able to communicate with the Mutating Webhook as described in #26. I believe Berglas should include at least the CA used by GCP Cloud Function (GTS Root R2) by default. That would help to avoid the need to rebuild containers just to add `ca-certificates` package. The CA cert can be added via `x509.SystemCertPool` as described [here](https://forfuncsake.github.io/post/2017/08/trust-extra-ca-cert-in-go-app/).

**Comment by sethvargo** [comment]
The default container does [include ca-certificates](https://github.com/GoogleCloudPlatform/berglas/blob/main/Dockerfile#L41). You shouldn't need to rebuild containers.

**Comment by jtyr** [comment]
That's the init container you pointing to. I'm talking about the container into which berglas is injected. If that container doesn't have `ca-certificates`, any SSL request (including the one to the Mutating Webhook) fails.

**Comment by sethvargo** [comment]
I'm still confused about which container you're "rebuilding" from your issue description? Can you tell me more about how you're currently using it?

**Comment by jtyr** [comment]
Let's say I have a Pod manifest which contains Container definition of an application serving API calls via HTTP. The application is written in Go and uses `alpine` Docker image as its base. Once I apply the Pod manifest, it gets sent to the Mutating Webhook which finds out that there is env var with `sm://...` reference so it starts mutate the pod definition by injecting the berglas init container and it also modifies the `command` of the application container to run `berglas`. The init container copies the `berglas` binary to a shared volume which is then mounted to the application container. Once the `berglas` runs in the application container, it fails if there is no CA. The CA could be baked into the `beglas` binary (or it could load it from the shared volume) to prevent this problem with missing CA.

**Comment by sethvargo** [comment]
> The application is written in Go and uses alpine Docker image as its base.

Why don't you install `ca-certificates` in that container? I really don't want to be in the business of maintaining CAs and CRLs lists inside Berglas.

**Comment by jtyr** [comment]
There is no problem if it's my own application for which I'm building my own Docker image. The problem comes when I want to use an image maintained by somebody else. If the person didn't include `ca-certificates`, I basically have to rebuild the container with the `ca-certificates` and maintain it by myself which brings huge overhead only for the benefit to be able to run Berglas with that container.

I understand that maintaining certs in the binary is perhaps not the best approach. But Berglas could be extended to read CA certs from a directory in the Berglas container (e.g. `/etc/berglas/certs`). Berglas would load those certs when it starts in the application container. You could by default include the "GTS Root R2" CA which is used by GCP services and expires on Jun 22 00:00:00 2036 GMT so not much maintenance is needed for the next 16 years. If people want to use their own CA, they could just build their own Berglas container based on top of your official container and add their CA there. That would changes the problem from maintaining many application containers to maintaining only one extra container.

**Comment by jtyr** [comment]
Any more thoughts on this?

**Comment by sethvargo** [comment]
I really don't think Berglas should be in the business of managing CA certs.

**Comment by jtyr** [comment]
Would you at least support the possibility to load a CA cert provided by the user? I believe that it's a real problem to force users to rebuild many application containers only for Berglas to function correctly. I would personally prefer to rebuild single container (berglas) instead of many application containers (all containers which don't have CA carts built in).

**Comment by sethvargo** [comment]
How would that help? You'd still need a CA cert somewhere to point to, which would involve rebuilding the container and building the CA cert.

**Comment by jtyr** [comment]
As I described above, the CA would be added into the user-built `berglas` container. Then the init container would copy the CA cert(s) to the same volume like `berglas` binary and when berglas starts, it would check if there are some CA certs in the pre-defined path and load them. I can try to create a PR with this feature so you can test it how it works.

**Comment by sethvargo** [comment]
There's a number of edge cases here, like what if the certs already exist at that point? Should we overwrite them? Should berglas use the certs in the supplied container or the certs in the target container?

Just like target containers need to declare a command to be compatible with berglas, I think it's reasonable to require that target containers also have CA certs for making TLS connections. I've documented this requirement in 5f099ce.
