### ISSUE TITLE
Parse berglas references of type SecretManager into childprocess environment

### ISSUE THREAD

**Issue by jawabuu** [GoogleCloudPlatform/berglas#147]
Hey @sethvargo 
Many thanks on this excellent project!
I'm trying to use berglas with secret manager to replace an environment value with the secret's contents but this always returns the file path `/tmp/berglas-12345`
From your docs, this is possible with berglas secrets
```
berglas exec -h
Parse berglas references and spawn the given command with the secrets in the
childprocess environment similar to exec(1). This is very useful in Docker
containers or languages that do not support auto-import.
```
Can the same be achieved with secret manager?

**Comment by jawabuu** [comment]
Actually just confirmed this works as expected with
`export PASSWORD=sm://project/secret; berglas exec -- env | grep PASSWORD`
I am however facing some difficulty in getting this to work

```
export PROXY_AUTH=sm://project/secret; berglas exec -- chisel client --auth $PROXY_AUTH proxy.com 127.0.0.1:1080:socks
```
In this case the env is provided as an argument.
Workarounds that solve the issue
```
export PROXY_AUTH=sm://project/secret; chisel client --auth $(berglas access $PROXY_AUTH) proxy.com 127.0.0.1:1080:socks
```
Any pointers as to why the 1st invocation does not work?
Feel free to close the issue as the problem seems to be in how the program is invoked.

**Comment by sethvargo** [comment]
The first invocation doesn't work because your _shell_ is processing the environment variable before it's passed to Berglas.

**Comment by jawabuu** [comment]
Thank you @sethvargo Would like your thoughts on a budget gke terraform module I'm creating once done.
