### ISSUE TITLE
Docker registry missing 0.5.3 tag

### ISSUE THREAD

**Issue by robcharlwood** [GoogleCloudPlatform/berglas#148]
Hello! :wave: 

Many thanks for this really useful tool!
I'd like to pin the latest version of the docker container to ``0.5.3``, however the Google Container registry only seems to have this image tagged with the version of ``latest`` rather than ``latest`` and ``0.5.3``. This means I am currently unable to pin my version dependencies accurately unless I want to use a slightly older version of ``berglas``. Is there any chance somebody kind could apply the missing tag to the image in the Google container registry? I can build from source or pull from cloud storage of course, but getting a fix in for the docker tag would be very useful.

Kind regards,
Rob

**Comment by sethvargo** [comment]
Hi @robcharlwood 

As [documented in the README](https://github.com/GoogleCloudPlatform/berglas#prerequisites):

> Note: the `gcr.io/berglas/berglas:latest` image remains for backwards compatability, but new versions are **not** published there.

Images are available at:

```text
asia-docker.pkg.dev/berglas/berglas/berglas
europe-docker.pkg.dev/berglas/berglas/berglas
us-docker.pkg.dev/berglas/berglas/berglas
```

And tagged versions are also available there:

```text
docker pull asia-docker.pkg.dev/berglas/berglas/berglas:0.5.3
docker pull europe-docker.pkg.dev/berglas/berglas/berglas:0.5.3
docker pull us-docker.pkg.dev/berglas/berglas/berglas:0.5.3
```

Please let me know if you have any questions.

**Comment by robcharlwood** [comment]
@sethvargo Ah thank you Seth! My apologies, I must have missed that when I was following the docs for configuration. :) 

Thanks very much for your time. 👍  Appreciate it!
