### ISSUE TITLE
Specify a replication policy of SecretManager

### ISSUE THREAD

**Issue by sato-s** [GoogleCloudPlatform/berglas#149]
Is there any way to specify a [replication policy](https://cloud.google.com/secret-manager/docs/choosing-replication) of SecretManager?
I checked `berglas create --help`, but there's no such flags.

**Comment by sethvargo** [comment]
Bergman's only supports the "automatic" replication policy at this time. What is your use case for user-managed?

**Comment by sato-s** [comment]
HI @sethvargo 
I need to create resources in the specific region due to [this](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#example_error_message) organization policy

**Comment by sethvargo** [comment]
In that case, you can create the secret using the web UI or gcloud with the desired policy, then use Berglas to update the secret data.

**Comment by sato-s** [comment]
Thanks.
It worked!
