### ISSUE TITLE
Providing a blank value with `berglas exec` and the Google Secret Manager backend

### ISSUE THREAD

**Issue by brandondtb** [GoogleCloudPlatform/berglas#154]
There are certain situations where I'd like to be able to provide a blank value using `berglas exec` with Google Secret Manager.

One example is involves setting `SENTRY_DSN` to configure Sentry (https://sentry.io/welcome/). I have a corresponding secret in Google Secret Manager and a secret ref in my environment. In order to disable Sentry (which I want to do in some environments), the library specifies that `SENTRY_DSN` environment variable should be empty.

Is there any way to accomplish this with Berglas/Google Secret Manager? Google Secret Manager doesn't allow me to set an empty value for a secret version, and `berglas exec` will fail if it cannot find a version for a referenced secret.

As a workaround, I could handle the setting of this variable differently on a per-environment basis, but that is not my preference.

**Comment by sethvargo** [comment]
You could create the secret value as a single space character (` `) and call trim on it, but you're then paying $0.06 to store a space.

**Comment by brandondtb** [comment]
Sorry for my late reply. I did indeed wind up storing the space as a workaround to my current issue.

I've thought about solving this for my more general use case in a couple of ways:

1. Add a flag to `berglas exec` that would cause it to log inaccessible secrets at a warning/error level but not raise an exception.

2. Modify the berglas secret spec to add a querystring parameter instructing berglas that the secret should be considered optional.

In either case when used with `berglas exec` the missing secret would be a blank value in the environment.

A concern with either of these approaches is that they may wind up masking a more general issue with accessing secrets, although this may be minimal if the API response differentiates between missing secrets/versions and, for example, permission errors.

I was curious if you had any thoughts on either of these solutions and if you would be open to a PR implementing either approach.

**Comment by sethvargo** [comment]
Hi @brandondtb - I think there's conflation between "secrets" and "configuration" here. I would recommend having your non-secret configuration come from a different service like [Runtime config](https://cloud.google.com/deployment-manager/runtime-configurator).

**Comment by brandondtb** [comment]
I was unaware of Runtime Configurator but will check it out.

Currently for the project related to this issue we are using kubernetes configmaps to store a mix of non-secret configuration and references to secrets in Secret Manger, and then using berglas to inject the secrets as per the kubernetes example. This approach is being taken to support several services that were developed following [twelve-factor app guidelines
](https://12factor.net/config).

The issue with empty secrets is something we are running into in our non-production environments, where some secrets don't have values, and in that case the service expects the environment variable to be present but have an empty value. If GSM or `berglas exec` were able to support empty/missing values, that would allow me deploy these services in each environment in the most consistent way, with only the secrets present in GSM varying.

Hopefully I've done a good job of explaining my use case clearly. In most new services secrets and configuration are being handled in a different way, so  this issue does not come up.

**Comment by sethvargo** [comment]
Hey @brandondtb - thanks, I understand the use case, but I think it's out of scope for what we want to support in Berglas. If Berglas is given a secret, it expects that secret to exist. I'm hesitant to add behaviors or configuration which break that guarantee, since I think this use case is very rare.

**Comment by brandondtb** [comment]
@sethvargo Definitely understand your view here. I will go ahead and close this issue and either implement this in a fork or find a different solution. Thanks for taking the time.
