### ISSUE TITLE
Signal sent after the process has finished

### ISSUE THREAD

**Issue by paalka** [GoogleCloudPlatform/berglas#163]
First of all, thanks for the great work on improving and providing support for Berglas! :)

The issue I have is that Berglas seems to send signals after the process has finished running.
To reproduce this issue, the following script should hopefully be sufficient:

```bash
#!/bin/bash
for i in {1..25} 
do
        berglas exec /usr/bin/true
done
```

When running the script above (on an Ubuntu 20.04 machine), I get the following output:
```
failed to signal command os: process already finished
failed to signal command: os: process already finished
failed to signal command: os: process already finished
failed to signal command: os: process already finished
failed to signal command: os: process already finished
```
These errors only sometimes occur, so you might have to run it multiple times for the commands to fail.
As you suggested in https://github.com/GoogleCloudPlatform/berglas/issues/36 it seems to occur less frequently with commands that run longer (ex. using `sleep 10` seems to on average yield less errors).

Just in case it could be useful – it seems like the [error](https://github.com/golang/go/blob/76b2d6afed1e22556bd6c52e74b546eb8bf9a225/src/os/exec.go#L18) is exported in the `os` golang module.
I can try to create a PR with a suggested fix if you don't have time to look into it.

**Comment by sethvargo** [comment]
Hey @paalka this is race condition because we need to start the signal handler _before_ starting the process, or else we risk losing a signal. However, doing so introduces the edge case where a process abruptly stops. In this case, the signal handler receives the exit and tries to forward to the child, but the child has already died.

In practice, most workloads do not encounter the race condition. Are you actually experiencing this in a production workload, or did you encounter the race theoretically?

**Comment by paalka** [comment]
> Hey @paalka this is race condition because we need to start the signal handler _before_ starting the process, or else we risk losing a signal. However, doing so introduces the edge case where a process abruptly stops. In this case, the signal handler receives the exit and tries to forward to the child, but the child has already died.
> 
> In practice, most workloads do not encounter the race condition. Are you actually experiencing this in a production workload, or did you encounter the race theoretically?

Aha! That makes sense! Thanks for the explanation :)
We encounter this relatively frequently when running [Argo Cron Workflows](https://argoproj.github.io/argo-workflows/cron-workflows/) on Kubernetes. The workflows primarily consists of simple python scripts that are run every 5-10 minutes or so. Berglas is in this case injected using the mutating webhook. I can try to provide an example of something similar to what we use it for, if that is useful.

In our case, this issue primarily just causes some noise in our monitors and logs.
I suppose we could have some issues with our setup, if this is something that doesn't really occur frequently elsewhere.

**Comment by sethvargo** [comment]
@paalka I think the best I could do in Berglas is suppress this particular error from appearing in logs. Would that help?

**Comment by paalka** [comment]
@sethvargo Hmm, I think that would help! Thanks a lot for the help btw :)
