### ISSUE TITLE
`berglas exec` requires credentials even when no secrets need to be decrypted

### ISSUE THREAD

**Issue by jappievw** [GoogleCloudPlatform/berglas#164]
I have an interesting use case. Our container is used in different environments. In one use case there are no Google credentials available, but `berglas` also doesn't need to decrypt anything. `berglas` still fails, because the credentials are not available. Is this intended behaviour?

**Steps to reproduce**

```
docker run -it --rm alpine
/ # wget https://storage.googleapis.com/berglas/main/linux_amd64/berglas
Connecting to storage.googleapis.com (172.217.17.48:443)
saving to 'berglas'
berglas              100% |********************************************************************************************************************************************************************************************************************************| 12.9M  0:00:00 ETA
'berglas' saved
/ # chmod +x berglas
/ # ./berglas exec -- echo yolo
failed to create berglas client: failed to create kms client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
/ # env
HOSTNAME=7cf45cffca67
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```

**Comment by sethvargo** [comment]
Hey @jappievw - this is kinda WAI since it doesn't really make sense to run Berglas without secrets. The instantiation of a berglas resolver [creates multiple clients](https://github.com/GoogleCloudPlatform/berglas/blob/4c3b3529287a32bb1449b45724a1e7c96345ed6f/pkg/berglas/berglas.go#L79). Even if they aren't used, those clients will attempt to find ADC.

**Comment by jappievw** [comment]
Hey @sethvargo, thanks for your fast response. I understand your reasoning. As we don’t always know beforehand when the environment needs secrets to be fetched from GSM it would be convenient to not fail.

**Comment by sethvargo** [comment]
Hi @jappievw - it would be a significant refactor that pushes client initialization to be lazy-loaded (which also introduces concurrency challenges). Given this use case is outside of Berglas' intended use case, I don't think we'll be able to justify making this change. Sorry!
