### ISSUE TITLE
is berglas 0.6.2 the latest release

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/berglas#170]
👋  Just want to double check if 0.6.2 is the latest release.

- relates to https://github.com/Homebrew/homebrew-core/pull/86510

**Comment by sethvargo** [comment]
Yea - 0.6.2 is the latest release. Not sure why that Homebrew PR was closed though

**Comment by chenrui333** [comment]
@sethvargo yeah, it was closed because the tag was not marked as `latest release`, do you mind flipping the flag, I can reopen my PR to update on the homebrew side, thanks!

**Comment by sethvargo** [comment]
Done. I didn't know Homebrew operated off of "releases" (I thought it used tags). Sorry!

**Comment by sethvargo** [comment]
https://github.com/GoogleCloudPlatform/berglas/releases/tag/v0.6.2
