### ISSUE TITLE
Change berglas exec to use sys.Exec?

### ISSUE THREAD

**Issue by thegoodlittlescript** [GoogleCloudPlatform/berglas#171]
We are using `berglas exec` in k8s, and we've run into the same issue outlined in these issues:

- [failed to signal command: os: process already finished Exited with code 2](https://github.com/GoogleCloudPlatform/berglas/issues/36)
- [Signal sent after the process has finished](https://github.com/GoogleCloudPlatform/berglas/issues/163)

Looks to me like you've taken some steps to address this 0.6.0, but we're still experiencing it in 0.6.2.  The end result is that occasionally our CronJob exits, errors as above (non-zero), and re-runs.

I wonder, should `berglas exec` actually `exec` as in [sys.Exec](https://pkg.go.dev/golang.org/x/sys@v0.0.0-20211106132015-ebca88c72f68/unix#Exec)? That way the command would replace berglas and all signal handling would be done directly on the process. Is that an approach you'd be open to?

**Comment by sethvargo** [comment]
Hi @thegoodlittlescript 

The primary reason it behaves this way is that I had a vision (not implemented) that you could signal the berglas process and it would re-process the secrets (to check for updates) and re-spawn the process if values had changed. I'm not opposed to switching to exec, except I think it doesn't work on Windows?

**Comment by thegoodlittlescript** [comment]
Hi @sethvargo - I imagine you're right. I wonder however if working on windows should be a goal of this command. Basically I wonder if there should be different commands for the two different platforms.

```
berglas exec
berglas win-exec
```

For example, the origin of all this is signal handling but from everything I see signals are not really a windows thing:

- [Windows is not POSIX. It does not have signals.](https://stackoverflow.com/a/140174)
- "Signals are primarily used on Unix-like systems." - golang docs around [os.Signal](https://pkg.go.dev/os/signal)
- ... the internet goes on ...

Maybe that's a hint that exec on windows/unix should be allowed to be different? In my own work I've leaned on unix `exec` so that I don't have to get into things like signal handling. But honestly I haven't had to design anything cross-platform and I don't know good patterns for it.

**Comment by sethvargo** [comment]
I'll look into it.

**Comment by sethvargo** [comment]
Let me know if that works for you ^

**Comment by thegoodlittlescript** [comment]
I built this, deployed it, and have been watching it all day. It seems fine -- the process is still working. Secrets appear to be set as before and as expected there are no more error messages around signals.

Thanks for the quick turnaround! I look forward to seeing this in a future release. Also fwiw I think your design around berglas refs is excellent. Being able to treat secrets like configs has been very helpful. Both our devs and SREs appreciate how visible everything is now.
