### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/berglas#194]
It looks like [1.0.0-beta1](https://github.com/GoogleCloudPlatform/berglas/releases/tag/v1.0.0-beta1) release was marked as latest release, raising an issue to confirm if that is intended.

relates to https://github.com/Homebrew/homebrew-core/pull/108192

**Comment by sethvargo** [comment]
Hmmm - https://github.com/GoogleCloudPlatform/berglas/releases/tag/v1.0.0 is the latest release. I released the -beta1 version to test the CI/CD was working properly on tag push before releasing v1.0.0. I'm not sure if there's a way to tell GitHub which release is the "latest".

They are from the same commit (https://github.com/GoogleCloudPlatform/berglas/commit/f28e74cca104f7d206bdabf153b97e145ceac786) and therefore should be identical.

**Comment by chenrui333** [comment]
yeah, that is cool, just to confirm if that is intended. Thanks for the quick reply, appreciate it!
