### ISSUE TITLE
1.0.0 image breaks kubernetes integration

### ISSUE THREAD

**Issue by brandondtb** [GoogleCloudPlatform/berglas#195]
The new 1.0.0 that was pushed today breaks existing kubernetes cluster integrations implemented as described in `examples/kubernetes`.

The new container image moves the `berglas` binary to a different location, and the webhook code uses the `latest` tag and references the previous location.

**Comment by brandondtb** [comment]
A couple of other notes:

The webhook code appears to no longer work with Cloud Functions, due to version incompatibilities. 

The `ghcr.io` image referenced in the webhook doesn't appear to be valid.

**Comment by brandondtb** [comment]
Also, I'd be happy to submit a PR related to the kubernetes integration example as I'm currently working on it.

**Comment by sethvargo** [comment]
Hi @brandondtb 

Thank you for opening an issue, and I'm sorry the release is a bit different. I didn't intend to move the binary (https://github.com/GoogleCloudPlatform/berglas/pull/196).

The Kubernetes webhook shouldn't use Cloud Functions anymore - I updated the guide to use Cloud Run a few weeks ago. Let me know if there's a spot I missed.

Good catch on the ghcr.io - that was left over from when I was testing the new release process (https://github.com/GoogleCloudPlatform/berglas/pull/197).

**Comment by brandondtb** [comment]
Thank you for responding so quickly. I'll look over the kubernetes docs/code  tomorrow and follow up here if I see anything.

**Comment by sethvargo** [comment]
Okay - I'll wait to hear back to cut 1.0.1.

**Comment by brandondtb** [comment]
Hi @sethvargo, the only thing I noticed was a reference to Cloud Functions in the second paragraph of the readme in the kubernetes example. Otherwise all looks good to me.

Thanks!
