### ISSUE TITLE
using secret account credentials.json instead of workflow identity

### ISSUE THREAD

**Issue by mikejoseph-ah** [GoogleCloudPlatform/berglas#199]
### Context

I am looking to use a k8s secret with my service account's key instead of updating my node pools, is there such way?

**Comment by sethvargo** [comment]
Hi @mikejoseph-ah 

We recommend against storing a service account key JSON in a k8s secret. If you want to go this route, please see the [documentation on Kubernetes secrets in GKE](https://cloud.google.com/kubernetes-engine/docs/concepts/secret).
