### ISSUE TITLE
version only shows as "source" if i go install

### ISSUE THREAD

**Issue by gedw99** [GoogleCloudPlatform/berglas#205]
would be nice if it the real version showed when i installed using go install.

``` 
go install github.com/GoogleCloudPlatform/berglas@v1.0.1
berglas -v
source
```

**Comment by sethvargo** [comment]
Hi there - the version information is injected as part of the build process; Go isn't really aware of specific tags unfortunately. The only option would be to manually set the string version in source, but that has historically been very error prone.

Berglas isn't really intended to be "go gettable".

**Comment by sethvargo** [comment]
It would be the full module path:

```

hey @sethvargo

No worries. Thanks for fast response.

The -ldflags trick below does not work. i guess because its internal or i messed up the package path.

If you see the error of my ways please feel free to let me know :)

go install -ldflags="-X 'github.com/GoogleCloudPlatform/berglas/internal/version.Version=$(BERGLAS_BIN_VER)'" github.com/GoogleCloudPlatform/berglas@$(BERGLAS_BIN_VER)
```
