### ISSUE TITLE
RFE: Kubernetes secret volume support

### ISSUE THREAD

**Issue by wstrange** [GoogleCloudPlatform/berglas#23]
It looks like the current implementation handles berglas env variable references.

It would be nice to be able to mount K8S secret volumes that reference berglas secrets. Not 100% sure how it work - but perhaps if the opaque secret starts with berglass://  it indicates that the actual value should be pulled from berglas?

**Comment by sethvargo** [comment]
You can specify `?destination=/var/foo/bar` on the berglas:// URLs today. That will write the secret contents to a file. Then you can share that folder as an in-memory volume mount, so that's all possible today 😄
