### ISSUE TITLE
Please provide new release with newest go version

### ISSUE THREAD

**Issue by brot** [GoogleCloudPlatform/berglas#234]
Version 1.0.3 of berglas is using go 1.20.4. But there were already 2 security releases after that
* 1.20.5: https://groups.google.com/g/golang-announce/c/q5135a9d924
* 1.20.6: https://groups.google.com/g/golang-announce/c/2q13H6LEEx0

So it would be great to bump the go version to the latest 1.20.6 and release a new berglas version. Thanks

**Comment by sethvargo** [comment]
Hi @brot - my plan is to cut a new version when Go 1.21 is released, since there's some functionality in there that reduces our overall dependency tree. None of the security issues in 1.20.5 or 1.20.6 are impactful to this project, and Go 1.21 is slated to be released in August.

**Comment by eestolano** [comment]
Hi @sethvargo, since Go 1.21 is out, any chance you could do another release?

**Comment by sethvargo** [comment]
v2.0.0 is out.
