### ISSUE TITLE
Mutating Webhook setup for K8S is missing

### ISSUE THREAD

**Issue by a7ul** [GoogleCloudPlatform/berglas#257]
I can no longer find an example to setup a kubernetes mutating webhook for berglas

As per the instructions in the readme, there should be a way to do:

> Kubernetes - Kubernetes pods can consume Berglas secrets by installing a [MutatingWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/). This webhook mutates incoming pods with the [berglas:// reference syntax](https://github.com/GoogleCloudPlatform/berglas/blob/main/doc/reference-syntax.md) in environment references to resolve at runtime. This integration works with any container, but all pods requesting berglas secrets must set an command in their Kubernetes manifests.

This existed in an example before but now there are no futher instructions

**Comment by sethvargo** [comment]
Hi @a7ul - I removed all the examples in #253 because it was too costly to manage all the dependency updates and CVEs. People were blocked using Berglas because scanners found vulnerabilities in unused dependencies in the examples.

The examples exist in older copy of the repository.
