### ISSUE TITLE
The mutating webhook is breaking sidecar containers

### ISSUE THREAD

**Issue by SergeyKanzhelev** [GoogleCloudPlatform/berglas#264]
See report here: https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/Pod-has-a-restartable-init-container-and-the-SidecarContainers/m-p/764743#M2072

Short term the API needs to be bumped to the latest: https://github.com/GoogleCloudPlatform/berglas/blob/f69dc2be6e7d2f6647920b64d37adb1b88dc8d4d/examples/kubernetes/go.mod#L9

Long term, Patch API would work better as it will not strip the Pod of unknown fields.

**Comment by SergeyKanzhelev** [comment]
Oh, I see. Example is using the https://github.com/slok/kubewebhook which does not support patch updates. Not an easy switch. For the long term best practice I still suggest to look into rewriting to the patch updates of Pods

**Comment by sethvargo** [comment]
Hi @SergeyKanzhelev - the `examples` folder was removed over two years ago, because the cost of maintaining them was too high (and they were _examples_, not production-ready code).
