### ISSUE TITLE
failed to signal command: os: process already finished Exited with code 2

### ISSUE THREAD

**Issue by inductor** [GoogleCloudPlatform/berglas#36]
It does not always happen, but on CI I sometimes get this error when using berglas with another app(in this case, terraform) with spawning a child process.

**Comment by sethvargo** [comment]
Hi @inductor 

Thank you for opening an issue. Can you please provide more information? That error indicates that `berglas exec` tried to start a command and the command exited too quickly. What command are you running exactly? Can you share more about your setup, possibly some code so I can try to reproduce it?
