### ISSUE TITLE
how to use berglas with kubernetes daemonset?

### ISSUE THREAD

**Issue by sonots** [GoogleCloudPlatform/berglas#37]
I did setup my kubernetes cluster following https://github.com/GoogleCloudPlatform/berglas/tree/master/examples/kubernetes.
It seems working fine for usual pods.
But, berglas does not work well for daemonsets becasuse of either MutatingWebhookConfiguration or because sidecar does not start for daemonset.

Could you tell me how to use berglas with daemonset? I want to use datadog-agent https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=k8sfile#create-manifest and want to use berglas for `DD_API_KEY`.

**Comment by sethvargo** [comment]
It should work, but you may need to [change this](https://github.com/GoogleCloudPlatform/berglas/blob/master/examples/kubernetes/deploy/webhook.yaml#L18) to include `daemonsets`.

**Comment by sonots** [comment]
I tried

```
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1", "v1beta1"]
    resources: ["pods", "daemonsets"]
```

But, I get errors

```
datadog-agent-tfrws datadog-agent 2019-07-11 23:54:55 UTC | CORE | ERROR | (pkg/forwarder/transaction.go:179 in Process) | API Key invalid, dropping transaction for https://6-12-1-app.agent.datadoghq.com/intake/?api_key=*************************rglas://<bucket_name>/datadog_api_key
```

**Comment by sonots** [comment]
I got it. I needed to specify `command`. Following change made it work. Thanks!

```
      containers:
      - name: datadog-agent
        image: datadog/agent:latest
         imagePullPolicy: Always
+        command: ["/init"]
```

**Comment by sethvargo** [comment]
Ah yes, this is [documented at the bottom](https://github.com/GoogleCloudPlatform/berglas/tree/master/examples/kubernetes#limitations). The command is needed because Kubernetes can't introspect the command set in the Dockerfile - it has to be set in the manifest.
