### ISSUE TITLE
Support for GAE

### ISSUE THREAD

**Issue by maroux** [GoogleCloudPlatform/berglas#42]
This seems like it should work just like Cloud Run, except it just hasn't been done yet - is that correct? If so, I can take this on..

**Comment by sethvargo** [comment]
It will work fine in GAE Flex. I'm not sure about GAE standard because I didn't try it. 

It will work on any product that provides Default Application Credentials.

**Comment by maroux** [comment]
Ok, I have a PR ready for this but haven't tested yet. Will put it up once I test it.
