### ISSUE TITLE
Question about newlines

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleCloudPlatform/berglas#61]
Hi,

I run into an issue when using berglas locally with `berglas exec --local`. It seems a newline character is added to the decrypted environment variable, which isn't a part of the originally encrypted secret. 

Here is a detailed walkthrough of my testing with this, and a reproduction path:

* create secret:
```
$ echo 'testsecretwithoutnewline' | berglas create berglas-wietse/testsecret -  --key projects/berglas-wietse/locations/global/keyRings/berglas/cryptoKeys/berglas-key
Successfully created secret [testsecret] with generation [1569245517544173]
```

* Validate it's there:
```
$ berglas access berglas-wietse/testsecret
testsecretwithoutnewline
```

* Validate there is no newline
```
$ TESTENV=$(berglas access berglas-wietse/testsecret)
$ echo "ONE${TESTENV}TWO"
ONEtestsecretwithoutnewlineTWO
```

* Use berglas exec 
```
$ export TESTENV=berglas://berglas-wietse/testsecret
$ berglas exec --local ${SHELL}
$ echo "ONE${TESTENV}TWO"
ONEtestsecretwithoutnewline
TWO
```

As you can see, in the berglas exec environment, a newline at the end of the secret is suddenly added.

**Comment by wmuizelaar** [comment]
Added info about my environment locally:

```
$ echo $SHELL
/usr/local/bin/bash
$ /usr/local/bin/bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by sethvargo** [comment]
```echo 'testsecretwithoutnewline'```

^ on most operating systems, this actually _does_ include a newline. Usually you need to pass the `-n` flag to tell `echo` not to include a newline. Does it reproduce if you use `echo -n ...`?

**Comment by wmuizelaar** [comment]
Ok, tested some more, and indeed, the secret is stored including the newline. Silly me :/
