### ISSUE TITLE
Kubernetes: support for envFrom?

### ISSUE THREAD

**Issue by rodrigoaliste** [GoogleCloudPlatform/berglas#62]
It would be awesome to have support for deployments with:

    envFrom:
        - secretRef:
            name: berglas://bucket/foo

where `bucket/foo` is a file such as:

    FOO=QkFSCg==

which is specially useful for deployments with hundreds of secret envs. Defining one `env:` per secret would be cumbersome.

**Comment by sethvargo** [comment]
Hi @rodrigoaliste 

While I agree that would be useful, it's not possible. You can use the [kubernetes example](https://github.com/GoogleCloudPlatform/berglas/tree/master/examples/kubernetes) to mutate pods via a custom webhook controller, but only via the filesystem. Kubernetes secrets [are not pluggable](https://github.com/kubernetes/kubernetes/issues/75899).
