### ISSUE TITLE
GAE Flex permission denied on decrypt

### ISSUE THREAD

**Issue by jasonjho** [GoogleCloudPlatform/berglas#63]
I've set up Berglas as well as the various IAM settings outlined in the Flex example README (using the flex service account), but when deploying I still get the following error:

```failed to access secret BUCKET_ID/my-secret: failed to access secret: failed to decrypt dek: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied for resource 'projects/MY_PROJECT/locations/global/keyRings/my_key_ring/cryptoKeys/my_key'.```

I've issued the `gcloud kms keys add-iam-policy-binding` command with `--member service-PROJECT_NUMBER@gae-api-prod.google.com.iam.gserviceaccount.com` assigned to the role `--role roles/cloudkms.cryptoKeyEncrypterDecrypter`, but still to no avail.

Any ideas or insights?  Thanks!

**Comment by jasonjho** [comment]
Turns out I had to apply the bindings to the AppEngine default service account (there are 2 for Flex) in addition to `service-PROJECT_NUMBER@gae-api-prod.google.com.iam.gserviceaccount.com`.

Not sure if this is unique to my instance or if the docs should be updated to reflect this.

**Comment by sethvargo** [comment]
I see a few things here:

- `my_key_ring` vs `my-key-ring`. Not sure if that's a typo or intended. Please ensure you're using the correct keyring ID

- The [AppEngine service account](https://cloud.google.com/appengine/docs/flexible/python/default-service-account) should be `PROJECT_ID@appspot.gserviceaccount.com`

**Comment by jasonjho** [comment]
Hi @sethvargo, thanks for clarifying. Yep, those typos were from just filling out the comment.

Follow up q:  is it then, necessary (as per the examples) to apply policy bindings to the other Flex serviceaccount?

**Comment by sethvargo** [comment]
Hi @jasonjho 

On all GAEs (Standard and Flex), the following SA exists:

```text
PROJECT_ID@appspot.gserviceaccount.com
````

_In addition to_ the standard SA, Flex includes an additional SA:

```text
service-PROJECT_NUMBER@gae-api-prod.google.com.iam.gserviceaccount.com
```

**Comment by jasonjho** [comment]
@sethvargo Yep, understood. From the Flex examples setup/readme, it says to grant the secret to:

```
SA_EMAIL=${PROJECT_NUMBER}-compute@developer.gserviceaccount.com
berglas grant ${BUCKET_ID}/my-secret-config --member serviceAccount:${SA_EMAIL}
```

Which service account should be granted. It would be helpful to understand why, if both or one of the other.

**Comment by sethvargo** [comment]
I think it's actually just `PROJECT_ID@appspot.gserviceaccount.com` for Berglas, but I don't/won't have time to test and verify that for a few weeks :frown:
