### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by maroux** [GoogleCloudPlatform/berglas#64]
Hey @sethvargo 

I'm looking to use a version with https://github.com/GoogleCloudPlatform/berglas/commit/a80844e0e4dff34f767bf12adb17d56330f79168.. Can I please get a new version (or an alternate way to download a binary with that commit? - I did check https://storage.googleapis.com/berglas/a80844e0e4dff34f767bf12adb17d56330f79168/linux_amd64/berglas which didn't work)

Thanks!

**Comment by sethvargo** [comment]
I just pushed 0.2.1. It should build and publish shortly. You can use this master build if you'd like: https://storage.googleapis.com/berglas/master/linux_amd64/berglas
