### ISSUE TITLE
Provide programmatic output

### ISSUE THREAD

**Issue by sethvargo** [GoogleCloudPlatform/berglas#66]
Provide a way to output in JSON or YAML for scripting and automation.

**Comment by vic3lord** [comment]
I'm not sure I mean the same thing but would be helpful to run berglas recursively on a directory and replace `berglas://` values in yaml files and output to stdout

**Comment by sethvargo** [comment]
Hi @vic3lord 

This issue is about providing machine-readable output (e.g. JSON) to be fed into other processes.

**Comment by vic3lord** [comment]
Thanks @sethvargo
