### ISSUE TITLE
Add a subcommand to generate a completion script

### ISSUE THREAD

**Issue by corneliusweig** [GoogleCloudPlatform/berglas#74]
Cobra has a builtin generator to create completion scripts for `bash` and `zsh`. Many projects make use of this generator, among others sigs.k8s.io/krew, k8s.io/minikube, or GoogleContainerTools/skaffold. This is usually used as `source <(berglas completion zsh)` in your shell, which then offers an improved CLI experience -- especially for new and casual users.

Is there a particular reason why `berglas` does not want that?

**Comment by sethvargo** [comment]
I think it was just an oversight. I'll try to get this into the next version.

**Comment by corneliusweig** [comment]
If you like I can get my hands dirty too.

**Comment by sethvargo** [comment]
https://github.com/GoogleCloudPlatform/berglas/commit/7552f02f5b752e2f749787ca8a1c91074307714c
