### ISSUE TITLE
enhancement: capability to add label to the secret bucket

### ISSUE THREAD

**Issue by mukgarg-lb** [GoogleCloudPlatform/berglas#79]
This bucket will be used to store the secret and the project can have multiple buckets.
There should be a capability to add labels like owner:name, classification: confidential to easily distinguished between the buckets to get a report.

**Comment by sethvargo** [comment]
You can always add labels to buckets via gsutil and the web interface. Berglas isn't designed to be a bucket management tool. Thanks!
