### ISSUE TITLE
Distribute binary releases

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/berglas#8]
Being able to just wget some url to get berglas would be useful.

**Comment by sethvargo** [comment]
That already exists and it's automated :smile:

See step 2 in the setup: https://github.com/GoogleCloudPlatform/berglas#setup

> Install a pre-compiled binary for your operating system:
> 
> - [darwin/amd64](https://storage.googleapis.com/berglas/master/darwin_amd64/berglas)
> - [linux/amd64](https://storage.googleapis.com/berglas/master/linux_amd64/berglas)
> - [windows/amd64](https://storage.googleapis.com/berglas/master/windows_amd64/berglas)
>
> This will download the latest version built against the master branch. To download a specific version, specify a git tag in place of "master" in the URL.

**Comment by ahmetb** [comment]
My bad, I was looking at the Releases tab, then skimmed the README and go-get + docker instructions got my attention instead.
