### ISSUE TITLE
403 while deploying the go example on Cloudrun GKE

### ISSUE THREAD

**Issue by PapaStan** [GoogleCloudPlatform/berglas#81]
Hi,

I'm trying to deploy the go example on Cloudrun on GKE and I'm getting this error :
```
panic: failed to resolve environment variables: failed to find environment variables: failed to communicate with cloud run: {
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED"
  }
```

The only command that is different from the README is the gcloud deploy command :
```
gcloud beta run deploy berglas-example-go \
  --project ${PROJECT_ID} \
  --platform gke \
  --namespace knative-serving \
  --cluster my-cluster \
  --region europe-west4 \
  --image gcr.io/${PROJECT_ID}/berglas-example-go:0.0.1 \
  --memory 1G \
  --concurrency 10 \
  --set-env-vars "API_KEY=berglas://${BUCKET_ID}/api-key,TLS_KEY=berglas://${BUCKET_ID}/tls-key?destination=tempfile"
```

Not that I had to remove the `--allow-unauthenticated` flag from the deploy command as it is not supported on GKE.

**Comment by sethvargo** [comment]
What permissions does your GKE cluster node service account have? Have you enabled workload identity?

**Comment by PapaStan** [comment]
Thank you for your quick reply,

After enabling and using Workload Identity, I'm facing another error:

```
failed to resolve environment variables: failed to find environment variables: failed to communicate with cloud run: {
    "error": {
        "code": 400,
        "message": "The request has errors",
        "status": "INVALID_ARGUMENT",
        "details": [
            {
                "@type": "type.googleapis.com/google.rpc.BadRequest",
                "fieldViolations": [
                    {
                        "field": "region",
                        "description": "Unsupported region europe-west4"
                    }
                ]
            }
        ]
    }
}
```

Is berglas using region-locked features?

**Comment by sethvargo** [comment]
It uses the regional endpoint to lookup environment variables. You can run berglas with `-local` and it wont try to contact the API. I haven't tested it with Cloud Run on Anthos because I presumed folks would just use the native Kubernetes stuff instead.

**Comment by PapaStan** [comment]
Ok, I'm closing the issue as CloudRun on Anthos is not supported.
Thank you for your time

**Comment by sethvargo** [comment]
Well - it should be 😄

**Comment by PapaStan** [comment]
With the `--local` flag: 
```
failed to access secret project-id/tls-key: failed to access secret: failed to decrypt dek: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
```

It looks like the cluster's service account (_number_-compute@developer.gserviceaccount.com) is not used by berglas.

**Comment by sethvargo** [comment]
Hi @PapaStan 

You should be able to use Berglas with Cloud Run for Anthos with v0.4.0+. Make sure your underlying node pools have the `cloud-platform` scope (the default is less).
