### ISSUE TITLE
Problem after revoking access to a secret

### ISSUE THREAD

**Issue by skurtzemann** [GoogleCloudPlatform/berglas#86]
Hi,

First, thanks for this awesome tool !

I got an issue when I revoke access to a user on a given secret.
If this user has been granted access to others secrets we got a permission denied on KMS decrypt resource.

Here what I try

1. Create 2 secrets
```bash
berglas create sku-berglas_secrets/sku/test/secret1 1234 --key projects/sku-berglas/locations/global/keyRings/berglas/cryptoKeys/berglas-key

berglas create sku-berglas_secrets/sku/test/secret2 5678 --key projects/sku-berglas/locations/global/keyRings/berglas/cryptoKeys/berglas-key
```

2. Grant access to these secrets
```bash
berglas grant sku-berglas_secrets/sku/test/secret1 --member serviceAccount:test@sku-berglas.iam.gserviceaccount.com

berglas grant sku-berglas_secrets/sku/test/secret2 --member serviceAccount:test@sku-berglas.iam.gserviceaccount.com
```

3. Revoke access on `secret2`
```bash
berglas revoke sku-berglas_secrets/sku/test/secret2 --member serviceAccount:test@sku-berglas.iam.gserviceaccount.com
```

4. Access to `secret1`
```bash
berglas access sku-berglas_secrets/sku/test/secret1
```

I've got the following error
```bash
failed to access secret: failed to decrypt dek: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied on resource 'projects/proximis-berglas/locations/global/keyRings/berglas/cryptoKeys/berglas-key' (or it may not exist).
```

I look into code and in GCP console, and what I understand :
* `berglas revoke` operation will remove the role `roles/cloudkms.cryptoKeyDecrypter` for the given user but it doesn't take care if the same user has other granted secrets.
  * so decryption for theses secrets will fail.

**Comment by sethvargo** [comment]
This is correct and working-as-intended. The help output for `revoke` also says this:

```text
When executed, this command revokes the following IAM permissions for each
member:

  - roles/storage.legacyObjectReader on the Cloud Storage object
  - roles/cloudkms.cryptoKeyDecrypter on the Cloud KMS crypto key
```

**Comment by skurtzemann** [comment]
> This is correct and working-as-intended. The help output for `revoke` also says this:
> 
> ```
> When executed, this command revokes the following IAM permissions for each
> member:
> 
>   - roles/storage.legacyObjectReader on the Cloud Storage object
>   - roles/cloudkms.cryptoKeyDecrypter on the Cloud KMS crypto key
> ```

Thanks for your response.

Do you planned to have a feature to revoke access to a specific secret without revoking `roles/cryptoKeyDecrypter` ? 

Or as you say this is the intended working of `revoke` and it will not be changed ?

**Comment by sethvargo** [comment]
I'd be open to a flag that doesn't revoke the KMS permission, but the default has to stay as total revoke.
