### ISSUE TITLE
help with cloudrun and wordpress

### ISSUE THREAD

**Issue by dsgolfside** [GoogleCloudPlatform/berglas#90]
can anyone give a non programmer like me instructions on how to use Berglas to startup wordpress 

i'm looking at these directions:

First, we set the credentials to access to the database through environment variables (we use PHP function getenv):

```php
define( 'DB_NAME', getenv('DB_NAME')  );
/** MySQL database username */
define( 'DB_USER', getenv('DB_USER') );
/** MySQL database password */
define( 'DB_PASSWORD', getenv('DB_PASSWORD') );
/** MySQL hostname */
define( 'DB_HOST', getenv('DB_HOST') );
```

It would be correct to pass this sensitive data through secrets but they are not (currently) natively supported by Cloud Run: for the sake of simplicity we will just pass them as plain-text but for production deploy it is absolutely recommended to use one of the possible workarounds available here https://www.sethvargo.com/secrets-in-serverless/.

**Comment by sethvargo** [comment]
Hi @dsgolfside 

If you are using Cloud Run, take a look at the [examples/cloudrun folder in this repo](https://github.com/GoogleCloudPlatform/berglas/tree/master/examples/cloudrun). Even though there's no PHP example, the python or node example will get you on the right track. You need to update your container's entrypoint to start with `berglas exec`

Old Dockerfile:

```
ENTRYPOINT ['php', 'my-app']
```

New Dockerfile:

```
ENTRYPOINT ['berglas', 'exec', '--', 'php', 'my-app']
```

Does that help?
