### ISSUE TITLE
Add documentation instructions specific to private key creation

### ISSUE THREAD

**Issue by thinkjrs** [GoogleCloudPlatform/berglas#97]
@sethvargo Thanks so much for your amazing work with Berglas! 

I want to share a twenty-minute time burn for me that ended up being quite obvious, from which I think the community could benefit. As such, this may or may not be an _issue_, per se.

### Use case: creating a Berglas secret that consists of a private key used for signing
Specifically, I sign some jwt tokens with this key. Enter Berglas, which provides a wonderful way to keep this key in the Google Cloud Platform ecosystem (and throw it away on other physical machines!). 

I know it's pretty common to store ssh keys for access to repos, build pipelines, jump servers, etc..., just wanted to share this specific use.

### The issue encountered

Because an RSA private key starts with `-----BEGIN RSA PRIVATE KEY-----`, the commands as given in the README will fail with the (Berglas) user receiving a "bad flag syntax" error. There's an extremely simple solution to this, subshells (I'll demo bash):

**This will fail**
```bash
# the line below will fail
berglas create --key ${KMS_KEY} ${BUCKET_ID}/MY_PRIVATE_RSA_KEY "$(cat my-private-rsa-key)"
```

Adding a simple delineator, ` -- ` (watch the spaces!), **this will work**:
```bash
# the line below will fail
berglas create --key ${KMS_KEY} ${BUCKET_ID}/MY_PRIVATE_RSA_KEY -- "$(cat my-private-rsa-key)"
```

I am more than happy to rock a documentation PR to add an example of the above, if this would be helpful for others. Otherwise it's here for future travelers.

**Comment by sethvargo** [comment]
@thinkjrs thanks for opening an issue, and sorry you got stuck. The preferred way to do this is with pipes:

```text
$ cat my-private-rsa-key | berglas create --key ${KMS_KEY} ${BUCKET_ID}/MY_PRIVATE_RSA_KEY -
```

This is documented in the help output for create.
